### PR TITLE
split init function from workspacebrowser

### PR DESCRIPTION
**Pull request by TornaxO7**
This will clean up the init function without losing readability

### CODE REVIEW

**Comment by TornaxO7** [comment]
@flxzt before I do any other changes, I'd like to get your opinion about this PR first. Is it ok? Do you agree? I'm aware of your answer [here](https://github.com/flxzt/rnote/issues/292), but I still would like to split this up if it's fine for you xD

**Comment by TornaxO7** [comment]
@flxzt (ping)

**Comment by TornaxO7** [comment]
@flxzt (ping?) ;-;

**Comment by flxzt** [comment]
Please don't ping me all the time. I won't forget it, I'll answer as soon as I have time to look at it.

For this one, I don't really see the benefit. I think it makes the code more difficult to read when it is split into many different files and functions. And these functions are not reusable anyways, so there is not much point in them. Maybe just add some comments to blocks which initialize one part of the composite widget ?

And if the composite really gets too big, I would rather split it up into multiple smaller composite widgets and initialize them in the same way.

**Comment by TornaxO7** [comment]
> Please don't ping me all the time

ok, sorry about this!

**Comment by flxzt** [comment]
Actually maybe the part of splitting the setup for the file rows is not too bad. I still would not split it into a separate file, but have it as a function inside the workspace impl

**Comment by TornaxO7** [comment]
> For this one, I don't really see the benefit. I think it makes the code more
difficult to read when it is split into many different files and functions. And
these functions are not reusable anyways, so there is not much point in them.

The idea to split the code up into different function is not the usage, it's
rather its readability.

Here are my reasons why I like to move some codeparts to functions:
1. They reduce the needed information about the code to a single name.
If we take a look into my refactoring:
```rust
    pub fn init(&self, appwindow: &RnoteAppWindow) {
        let remove_workspace_button = components::setup_remove_workspace_button(self, appwindow);
        let edit_workspace_button = components::setup_edit_workspace_button(self, appwindow);
        let _add_workspace_button = components::setup_add_workspace_button(self, appwindow);

        components::setup_workspace_list(
            self,
            appwindow,
            &remove_workspace_button,
            &edit_workspace_button,
        );
        components::setup_workspace_listbox(self, appwindow);
        components::setup_files_prefix_listbox(self, appwindow);
        components::setup_file_rows(self, appwindow);

        self.setup_dir_actions(appwindow);
    }
```
you can see each single step of the init process. No need to scroll.
The main parts can be read by the function names.

2. Encapsulation
If you want to add *more* stuff to for example the file-rows, you can jump right
to the `setup_file_rows` functions to edit the relevant code about the
file-rows.

3. No-Comments
Ok, this might sound a bit harsh, since comments should normally help. For me,
comments like those:
```rust
        // Setup prefix listbox
        self.imp().files_prefix_listbox.connect_row_activated(clone!(@weak self as workspacebrowser, @weak appwindow => move |_, row| {
            if row == &workspacebrowser.imp().dir_up_row.get() {
                if let Some(parent_dir) = workspacebrowser.selected_workspace_dir().and_then(|p| p.parent().map(|p| p.to_path_buf())) {
                    workspacebrowser.set_current_workspace_dir(parent_dir.to_path_buf());
                }

            }
        }));

```
helped me to understand the code, when I read the code for the first time, but
when I read the comment, my brain is thinking: "Ok, understood, so I can skip
this paragraph", but then I need to scroll down to see the next
[paragraph]/[relevant code part] and I have to remember what I've already seen
(to understand its context). So why not "converting" the comments into functions
to understand the code?

I've only worked for 2 months in a company yet, but my team also said: It
doesn't matter if the function is only used once, it's just for better
readability and that's reason enough to do that.

4. Changes
Whenever I do some changes, I'm mostly just changing the relevant code to fix a
bug for example, but I do forget to update the comments, which is bad, because
wrong documentation is worse than no documentation.

---
> I still would not split it into a separate file, but have it as a function
  inside the workspace impl

I can live with this as long the init function can be reduced a bit :)
So are you going to reopen this PR?

---
> Please don't ping me all the time. I won't forget it, I'll answer as soon as I have time to look at it.

And sorry again about this ;-;

**Comment by flxzt** [comment]
Good points. I am also probably biased since I already know the code base very well.

> I can live with this as long the init function can be reduced a bit :)

Lets do it this way :) To keep it in one file, but split it up into multiple smaller ( private ) functions

> And sorry again about this ;-;

Don't worry about it!

**Comment by TornaxO7** [comment]
I just pulled the current the current state from the main branch and did `cargo check`but I'm getting the following error message:
```
    Checking rnote-compose v0.1.0 (/home/tornax/Programming/pull_requests/rnote/rnote-compose)
error[E0560]: struct `StrokeModelerParams` has no field named `prediction_params`
   --> rnote-compose/src/builders/penpathmodeledbuilder.rs:258:13
    |
258 |             prediction_params: PredictionParams::StrokeEnd,
    |             ^^^^^^^^^^^^^^^^^ `StrokeModelerParams` does not have this field
    |
    = note: available fields are: `wobble_smoother_timeout`, `wobble_smoother_speed_floor`, `wobble_smoother_speed_ceiling`, `position_modeler_spring_mass_constant`, `position_modeler_drag_constant` ... and 5 others

error[E0599]: no method named `reset_w_params` found for struct `StrokeModeler` in the current scope
   --> rnote-compose/src/builders/penpathmodeledbuilder.rs:266:29
    |
266 |         self.stroke_modeler.reset_w_params(params);
    |                             ^^^^^^^^^^^^^^ method not found in `StrokeModeler`

Some errors have detailed explanations: E0560, E0599.
For more information about an error, try `rustc --explain E0560`.
error: could not compile `rnote-compose` due to 2 previous errors
```
is that normal?

**Comment by TornaxO7** [comment]
ok eeeeeeeeh I think that I'll create a new branch because I'm veeeeery irritated by git at the moment.

**Comment by flxzt** [comment]
I think you would have needed to pull the updates in `ink-stroke-modeler-rs` submodule too.

**Comment by TornaxO7** [comment]
I guess you're right but I haven't worked with submodelus yet xD

**Pull request closed without merging**
