### PR TITLE
Add action to update chinese translations after pushes

### LINKED ISSUE #220: Suggestion for Chinese translations
I found that the completion of `Simplified Chinese`translation is way higher than the `Traditional Chinese` ( 90+% vs 70+%).
As `Simplified Chinese` and `Traditional Chinese` are the **SAME** language but in two different **WRITING FONTS**, I suggest that we just keep the Simplified Chinese active, and use the converter tool OpenCC([https://github.com/BYVoid/OpenCC](https://github.com/BYVoid/OpenCC)) to automatically generate the Traditional version of Chinese.
In this way, translators no longer need to maintain two **SAME** languages, and their work should be easier.

### PR DESCRIPTION
**Pull request by detiam**
resolve #220

### CODE REVIEW

**Comment by flxzt** [comment]
thank you. Can this be a separate workflow that only triggers when the `zh_hans` file actually changed through [this condition](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-affects-specific-files). It would also keep the CI workflow neat and clean

**Comment by detiam** [comment]
@flxzt ok updated

**Comment by flxzt** [comment]
alright, I tested it [here](https://github.com/flxzt/rnote-testing/actions/runs/6835465493/job/18589286936) but it fails in the last commit/push step.

**Comment by flxzt** [comment]
with that addition it seems to be working ( see [here](https://github.com/flxzt/rnote-testing/commit/9b78ceb9809f5f0bee7ef320c6df3934621dfa3b) ). However the workflow removes `zh_hans` from `LINGUAS which is probably not what we want because weblate will always add it again and there may be system configuration that support these meta locales?. It shouldn't be a problem if there are "zh_hans zh_hant" **and** the additional locales "zh_CN  zh_SG zh_HK zh_TW" in the LINGUAS file

**Comment by flxzt** [comment]
alright, this looks good to me now and seems to be doing what we want (see [here](https://github.com/flxzt/rnote-testing/actions/runs/6913076254)! Thank you!

**Comment by detiam** [comment]
@flxzt updated, my system ssd broken so it's been later, sorry @_@

**Comment by BobH-Official** [comment]
I just recieved email from weblate today, and noticed this pr. Thank you @flxzt for adoptting my suggestion #220. And thank you @detiam for implementing the code.

**Pull request merged**
