### PR TITLE
Adding mirorring-feature for selected shapes.

### PR DESCRIPTION
**Pull request by TornaxO7**
This should fix https://github.com/flxzt/rnote/issues/207.

### CODE REVIEW

**Comment by TornaxO7** [comment]
Where should be the "mirror-action"?
Should there be two action-buttons in my marked box?

image

Another idea would be, to have something like a single button on the bar which has the following features:
- The button displays either the horizontal or the vertical mirroring
- If it shows the horizontal mirroring for example, then the selected shapes will be mirrored horizontally
- If you hold it for a short time, two other buttons will pop up, where you can select horizontal or vertical mirroring

What do you think?

**Comment by PhilDevProg** [comment]
> Where should be the "mirror-action"?
> Should there be two action-buttons in my marked box?

That would be the easiest and in my opinion best way to do this.

> Another idea would be, to have something like a single button on the bar which has the following features:
> - The button displays either the horizontal or the vertical mirroring
> - If it shows the horizontal mirroring for example, then the selected shapes will be mirrored horizontally
> - If you hold it for a short time, two other buttons will pop up, where you can select horizontal or vertical mirroring

I think it would be confusing to hold the button to change it's action and it takes longer. And what about users with a mouse or a pen? Holding a button with a mouse or a pen isn't something you normally have to do.

**Comment by yuval-herman** [comment]
Perhaps a button placed directly inside the selection box could be more helpful and intuitive.
Example:
image

**Comment by TornaxO7** [comment]
Ok, I've to sadly announce that I may not have the time to approach this PR for the time being since I still can't get a [dev-environment to working](https://github.com/flxzt/rnote/discussions/813). If anyone has the time to approach this: Feel free to do! I'm sorry for this announcement :(

**Pull request closed without merging**
