### PR TITLE
Update it.po

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by flxzt** [comment]
this doesn't update any translation strings, was this unintentional?

**Comment by albanobattistella** [comment]
> this doesn't contain any translation string updates, was this unintentional?

Hi,
in the translation there was a double space and I removed it. :-)

**Comment by flxzt** [comment]
hm, the git diff only shows a removed line in between some translation strings, and the updated date. Maybe something went wrong with git? Btw I finally got around to integrating the hosted [weblate](https://hosted.weblate.org/projects/rnote/repo/) translation service, if you are one of the translators that prefer that. (if not, manual updates via PR's are still fine and very appreciatedl!)

**Comment by flxzt** [comment]
@albanobattistella Should I close this or do you want to update it with new translations?

**Comment by albanobattistella** [comment]
> Should I close this or do you want to update it with new translations?

You can close it, I'll update with the new strings. thanks. A.

**Pull request closed without merging**
