### PR TITLE
Suggestions for menu strings

### PR DESCRIPTION
**Pull request by mbousq**
Hi Felix. 
These are just some suggestions to potentially clarify menus in the app.

**What I found**
- The use of "Sheet" everywhere. When the user has "show format option" active, the user is exposed to, in a way, multiple sheets. Therefore, options such as clear sheet, save sheet and so on could infer saving _only_ the active "sheet". In this merged request, I changed "sheet" to "document" where necessary, while keeping "sheet" for "Sheet format", "Zoom to fit sheet width" etc.

- "Expand mode" to "Layout"
- "Endless vertical" to "Continuous vertical"
- "Export .." to "Export…"

Tell me what you think.

### CODE REVIEW

**Comment by flxzt** [comment]
Very good suggestions, I fully agree! Let me update the naming in the source too, and then the pot can be regenerated from it.

**Comment by mbousq** [comment]
By the way, I forgot another thing.  We have "Brush" in the header bar and "Pen sounds" in the menu. Not sure which terminology to keep between pencil or brush, or if you're planing on adding a brush sound :p

**Comment by flxzt** [comment]
Oh true. I guess "brush sounds" would be better

**Comment by mbousq** [comment]
And last one, Dot Radii, I don't quit understand the two values. The first one seems to relate to stroke thinckness and the second one is the radius ?

**Comment by mbousq** [comment]
ah Ok, got it. vertical and horizontal radius

**Comment by flxzt** [comment]
since you didn't understand it right away, this probably should also be updated with a clearer description..

**Comment by mbousq** [comment]
Maybe horizontal and vertical flattening ?

https://en.wikipedia.org/wiki/Flattening

**Comment by flxzt** [comment]
Not sure if that is more clear without context. My thought was to a more detailed explanation in the subtext.

Just so you are not confused when the strings are updated: I'll keep `pen sounds` for now, that'll leave me the option to extend them to other pen types in the future.

**Comment by flxzt** [comment]
What about "The radii of the individual dots in the textured stroke"

**Comment by mbousq** [comment]
Good idea !

**Comment by flxzt** [comment]
Ok great! Can you check the new generated .pot, if I missed something? I want to do a new fix release soon

**Comment by mbousq** [comment]
All good, at least as far as I can see :+1:

**Comment by flxzt** [comment]
Ok. Thanks!

**Pull request closed without merging**
