### PR TITLE
Move `Document Layout` and `Developer` preferences

### PR DESCRIPTION
**Pull request by silvasch**
This PR moves the `Document Layout` and the `Developer` preferences to the settings panel.

# Status
- [x] Document layout
  - [x] Add UI
  - [x] Implement behavior (inconsistencies when loading documents)
  - [x] Remove previous UI
- [x] Developer options
  - [x] Visual debugging
    - [x] Add UI
    - [x] Implement behavior
    - [x] Remove previous UI
  - [x] Export engine state
    - [x] Add UI
    - [x] Implement behavior
    - [x] Remove previous UI
  - [x] Export engine config
    - [x] Add UI
    - [x] Implement behavior
    - [x] Remove previous UI

### CODE REVIEW

**Comment by flxzt** [comment]
Thanks. Is it intentional that you didn't move the shortcuts section to its own page as discussed or is it outside of the scope of this PR for you?

The document-layout option looks good.

The developer options are now seen by normal users as well, which is not desirable. Also: it was an intentional choice not to restore the visual-debug option.
But to be really honest I still think the old menu was a better fit as a dev-menu where actions can be added quickly for testing purposes, why are you so eager to change it?

**Comment by silvasch** [comment]
This PR implements everything how I mentioned it in [this comment](https://github.com/flxzt/rnote/issues/938#issuecomment-1870551113). I thought this was how we ended up.

> Is it intentional that you didn't move the shortcuts section to its own page as discussed or is it outside of the scope of this PR for you?

As mentioned above, this PR just implements everything mentioned in the comment.

> The developer options are now seen by normal users as well, which is not desirable.

I know what you mean, but I'd argue that the current way is visible for normal users as well. If you want to hide the developer options, I would hide the options completely and make them visible using a keyboard shortcut (either in the app menu or in the settings page).

> Also: it was an intentional choice not to restore the visual-debug option.

I thought visual debugging was already being restored, but turns out I never really tested it.

> But to be really honest I still think the old menu was a better fit as a dev-menu where actions can be added quickly for testing purposes, why are you so eager to change it?

I'd like to change it because I think they are in the wrong place. Having a developer menu is something special that rnote has (at least I've never seen developer options in any other app). The only place I can see them fit are as settings in the settings menu.

Here's what I'm gonna do:
1. I'm going to change this PR to only move the document layout options.
2. I'm going to create a second PR to move the shortcuts to a new panel.
3. I'm going to leave the developer menu as is right now and think about a better solution.

**Comment by flxzt** [comment]
Sorry for the push, I accidentally did a chore on the wrong branch.


> Here's what I'm gonna do:

>    I'm going to change this PR to only move the document layout options.
>    I'm going to create a second PR to move the shortcuts to a new panel.
>    I'm going to leave the developer menu as is right now and think about a better solution.

Okay, that sounds good. That's what we can both agree on

**Comment by flxzt** [comment]
can I refactor  this to completion @silvasch ? I'd like to do a release soon

**Comment by silvasch** [comment]
Yes, you can. I have a lot to do at the moment, sorry.

**Comment by flxzt** [comment]
thanks, and no worries

**Comment by flxzt** [comment]
see #1006

**Pull request closed without merging**
