### PR TITLE
include angle libegl.dll

### LINKED ISSUE #839: Broken dynamic library link in windows
**Describe the bug**  
When I run the app on Windows using its shortcut, a pop-up titled “Entry Point Not Found” shows up, and it states the following: 

> The procedure entry point _ZN3egl10CreateSyncEP¨PvjPKx could not be located in the dynamic link library C:\Program Files\Neovim\bin\libEGL.dll.

The application opens app and functions, but I didn't work with that much to know the implications of the error.

Oddly enough, the error doesn't occur when I launch the app using PowerShell while been in the bin folder of the app.

**To Reproduce**  
1. Install the app
2. Open it using its shortcut
3. The error pop-up shows up

**Expected behavior**  
The app should open normally with the linking error pop-up.

**Screenshots**  

scr

**Desktop (please complete the following information):**  
 - OS: Windows 10 LTSC 1809
 - App Version: Rnote v0.9.0
 - Installation Source: GitHub releases

### PR DESCRIPTION
**Pull request by mdonoughe**
I haven't run a full build with these changes but copying these DLLs into my Rnote installation stops it from trying to find other libEGL.dll files on my system.

Fixes #839

### CODE REVIEW

**Comment by flxzt** [comment]
lgtm, thanks!

**Comment by flxzt** [comment]
this fix doesn't seem to fix it fully, some users still report issues related to a missing libegl.dll, see #978

**Comment by mdonoughe** [comment]
Hmm they shouldn't be able to _add_ libegl.dll because it's supposed to already be there. It doesn't seem like the files are making it into the installer.

**Comment by mdonoughe** [comment]
I copied the installer file staging code for the gdk pixbuf loaders, but how do the pixbuf loaders themselves get into the installer? It looks like maybe only the dependencies of the EGL dlls are being copied and not the EGL dlls themselves.

**Comment by flxzt** [comment]
The pixbuf loaders get included through the inno script `rnote_inno.iss.in` in the `[Files]` section. But you're right, the `libEGL*.dll` and `libGLES*.dll` themselves are not transferred, only their dependencies

**Pull request merged**
