### PR TITLE
Fix typos and add typos config

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `typos --format brief`.

### CODE REVIEW

**Comment by flxzt** [comment]
Thanks! I would add `.pot` files for exclusion too, and a glob for all `*LICENSE*` files.

**Comment by kianmeng** [comment]
> Thanks! Can you add `.pot` files for exclusion too, and a glob for all `*LICENSE*` files.

Done. But, the repo only have one `LICENSE` file?

```sh
$ find . | grep LICENSE
./LICENSE
```

**Comment by flxzt** [comment]
the submodules also have license files, if you init them. Also for future proofing

**Comment by kianmeng** [comment]
@flxzt Sorry I miss this one, but you've already merged.

**Comment by flxzt** [comment]
No problem, I added it myself right after merging

**Pull request merged**
