### PR TITLE
Apply clippy suggestions

### PR DESCRIPTION
**Pull request by TornaxO7**
I looked, if `clippy` had some suggestions and tried to apply them. Some cases need a little discussion before changing anything.

### CODE REVIEW

**Comment by TornaxO7** [comment]
```rust
warning: this function has too many arguments (8/7)
   --> rnote-compose/src/style/rough/roughgenerator.rs:428:1
    |
428 | / pub(super) fn compute_ellipse_points<R>(
429 | |     increment: f64,
430 | |     center: na::Vector2<f64>,
431 | |     radius_x: f64,
...   |
436 | |     rng: &mut R,
437 | | ) -> (Vec<na::Vector2<f64>>, Vec<na::Vector2<f64>>)
    | |___________________________________________________^
    |
    = note: `#[warn(clippy::too_many_arguments)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#too_many_arguments
```
this is another output of `cargo clippy`. I'm unsure what might be the best for this one.

**Comment by TornaxO7** [comment]
```rust
warning: very complex type used. Consider factoring parts into `type` definitions
   --> rnote-engine/src/engine/import.rs:283:10
    |
283 |     ) -> oneshot::Receiver<anyhow::Result<Vec<(Stroke, Option<StrokeLayer>)>>> {
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(clippy::type_complexity)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#type_complexity
```

**Comment by TornaxO7** [comment]
```rust
warning: all variants have the same prefix: `k`
 --> /home/tornax/Programming/pull_requests/rnote/target/debug/build/ink-stroke-modeler-rs-668b4ec6d4f613be/out/autocxx-build-dir/rs/autocxx-ffi-default-gen.rs:1:25988
  |
1 | ...ve (Clone , Hash , PartialEq , Eq)] pub enum Input_EventType { kDown = 0 , kMove = 1 , kUp = 2 , } # [repr (C , align (8))] pub struct...
  |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(clippy::enum_variant_names)]` on by default
  = help: remove the prefixes and use full paths to the variants instead of glob imports
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#enum_variant_names
```

**Comment by TornaxO7** [comment]
```rust
warning: avoid using `collect()` when not needed
   --> rnote-engine/src/store/render_comp.rs:212:50
    |
212 |         let keys = self.render_components.keys().collect::<Vec<StrokeKey>>();
    |                                                  ^^^^^^^
213 |
214 |         keys.into_iter().for_each(|key| {
    |         ---------------- the iterator could be used here instead
    |
    = note: `#[warn(clippy::needless_collect)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_collect
help: use the original Iterator instead of collecting it and then producing a new one
    |
212 ~
213 |
214 ~         self.render_components.keys().for_each(|key| {
    |
```
I think this can be ignored because glueing the stuff in a row: `self.render_components.keys().for_each(|key| {...` leads to a double reference of `self` which is `&mut self` hence we're getting an error here.

**Comment by TornaxO7** [comment]
Those are the other warnings from `cargo clippy`. Feel free to post your opinion on those of what you think should be done with them.

**Comment by flxzt** [comment]
Hey, again thanks. I wanted to review all clippy suggestions myself and fixed them (or added exceptions) manually in 49b5634c6c919c9be0b98d665b2cce9999f321c6 .

**Comment by TornaxO7** [comment]
Well, that's possible as well ^^

**Pull request closed without merging**
