### PR TITLE
Add confirmation prompt to deletion action

### LINKED ISSUE #1136: prompt for confirmation when removing folders
**Describe the bug**  
I deleted the 'Documents' directory from the Default Workspace, corresponding to '~/Documents' linux directory.

The directory was permanently deleted, and not even a user dialog warning about this was issued.

The deleted directory wasn't moved to the Trash bin, it was permanently deleted.

I tried recovering it with the Linux tool 'testdisk' without success.

**To Reproduce**  
1. Go to the Workspace
2. Delete a directory

**Expected behavior**  

The deleted directory should have been moved to the Trash bin, or at least warn me that it was going to be permanently deleted.

**Console Output**  

I can't provide the output because I turned off the computer to try to recover the deleted data with 'testdisk' Linux utility. I'm afraid that turning it on again will overwrite the unallocated disk sectors that were originally occupied by the deleted data.

**Desktop**  
 - OS: Kubuntu 22.04
 - App Version: Rnote v0.10.2
 - Installation Source: Flatpak
 - Desktop Environment: KDE Plasma 5.24 
 - Display Server: Wayland
 - Input Source: Mouse and Keyboard, External Graphics Tablet

### PR DESCRIPTION
**Pull request by RayJW**
New PR which closes #1192 since this branch had a bunch of tedious merge conflicts.

resolve #1136

### CODE REVIEW

**Comment by flxzt** [comment]
looks good to me! 


Only a small change is needed to satisfy clippy.

**Comment by RayJW** [comment]
> Only a small change is needed to satisfy clippy.

Done, I think this should be ready for merging now if everyone agrees :)

**Comment by RayJW** [comment]
Oh, and obviously resolves #1136 just so the PR is linked to the issue.

**Comment by flxzt** [comment]
Do you want to add yourself to the `AUTHORS` file?

**Comment by RayJW** [comment]
> Do you want to add yourself to the `AUTHORS` file?

Sure, I went ahead and added my username. Thanks! :)

**Pull request merged**
