### PR TITLE
Remove redundant sidebar tool icons 

### PR DESCRIPTION
**Pull request by martin-desktops**
Closes https://github.com/flxzt/rnote/issues/239

### CODE REVIEW

**Comment by flxzt** [comment]
Hey, thanks for the PR. I am not sure this is actually what I want, since the first sidebar controls are awkwardly in the corner. Can you post a screenshot how it then looks? I am inclined to keep the icons or simply replacing them with empty space if the argument is that it is too cluttered visually.

**Comment by martin-desktops** [comment]
Hello! Here you are

PR version:

Screenshot from 2022-12-23 15-00-13

Pre PR:
Screenshot from 2022-12-23 15-00-30

For me, a clutter wasn't the issue, Rnote's UI is quite simple.  Something just feels off that exactly the same icons are next to each other, it feels redundant, and two icons don't give more cues that one, and because one, highlighted one is enough, the second makes me think "Is it a clickable button?", "why there's another, exactly the same icon?". It's confusing.

Screenshot from 2022-12-23 15-04-12

**Comment by flxzt** [comment]
Right, that is a good point. I don't like it when the icons are simply removed though. What we could do, is have a spacer there instead of the icon and bind its visibility to when "revealed" property of the pen toggle revealer.

**Comment by martin-desktops** [comment]
I would love to see that solution in practice, but I am worried it's beyond my skills. I am not a programmer, here, I just removed a bunch of lines :)

**Comment by flxzt** [comment]
Ah, no worries then. Here is how I solved it:


https://user-images.githubusercontent.com/19841886/209436346-ed6ffd09-ef0d-41e6-963e-97fdd82b9648.mp4

**Comment by martin-desktops** [comment]
Thanks for consideration! 

The space separating a horizontal bar from the vertical one is definitely on place here, so the first item in the tool setting bar doesn't look like another tool. 

One thing that doesn't look right for me though is this rectangle made by these two light gray lines. I think it would look cleaner without them, or at least without the horizontal one, since the vertical one seperates these two bars without creating an empty rectangle.

Screenshot from 2022-12-24 13-41-58

**Comment by flxzt** [comment]
Tried that too, it looks odd without it. I think I'll keep it for now

**Pull request closed without merging**
