### PR TITLE
Bump GNOME runtime and LLVM version

### PR DESCRIPTION
**Pull request by RayJW**
This is just pure maintenance PR. This bumps the GNOME runtime to 47 and LLVM to 18. I tested both changes and everything works fine. I've used the changes for a bit doing my regular work with all kinds of different tools and tasks, everything seemed fine and maybe even a bit smoother (although that might easily be placebo). It probably still makes sense to test this for a bit before applying to the Flatpak, which is why I opened the PR here instead of on Flathub. Although I've never seen a runtime change break something if building worked fine.

### CODE REVIEW

**Comment by RayJW** [comment]
I just realized I misread something somewhere. It seems like LLVM 18 is compatible with Rust 1.78 not 1.74, not sure where the mistake was on my side, but I'll revert that then to avoid any hidden consequences.

**Comment by RayJW** [comment]
Seems like this might be less of a hassle than I initially thought. It seems like [LLVM 17 won't get a 24.08 branch](https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm17/pull/7) due to being EOL, so it won't be possible to bump GNOME to 47 either since that doesn't have a 23.08 branch. I'm not sure if upping the minimum Rust version is viable.

**Comment by flxzt** [comment]
Thank you!. Bumping Rust's MSCV should be fine in my opinion.

**Comment by RayJW** [comment]
I used the [cargo-msrv](https://crates.io/crates/cargo-msrv) crate to check the compatibility and updated to the successful 1.79 version. Everything still compiles fine and seems to be working great so far :)

**Comment by RayJW** [comment]
I bumped the MSRV to the latest Rust version (1.81) now since I don't see a reason to use a EOL version. I think that mostly makes sense for crates that are supposed to be used as dependencies.

**Pull request merged**
