### PR TITLE
Added Hebrew translation

### PR DESCRIPTION
**Pull request by yarons**

### CODE REVIEW

**Comment by yarons** [comment]
I would also like to suggest using a translation platform such as Weblate which should make the pushing and pulling redundant.

Thank you.

**Comment by flxzt** [comment]
Hi, thanks for the translation!
And I agree. (it is actually the very first reported issue, #1).

**Comment by flxzt** [comment]
@yarons I finally applied for the hosted weblate service, you can find the weblate repo here: https://hosted.weblate.org/projects/rnote/repo/

**Comment by yarons** [comment]
Thanks @flxzt , you are the best!

**Pull request merged**
