### PR TITLE
Update symbolic icons

### PR DESCRIPTION
**Pull request by oscfdezdz**
Noticed that some icons were outdated and updated them with the latest changes from https://gitlab.gnome.org/GNOME/adwaita-icon-theme.

`remove-page-symbolic` is a modification based on `add-page-symbolic` and `text-indent-more-symbolic` of `text-indent-less-symbolic`.

### CODE REVIEW

**Comment by flxzt** [comment]
nice, thanks!

going through the icons, I noticed some differences in the icon scaling for a few icons. Some were intentionally scaled down by 0.5x because they are used in the 32px size in the app (mostly in the tool bars), and a full size icons are too large in those places. So the new ones would need that adjustment as well.

- pen-tools-offsetcameratool-symbolic
- pen-typewriter-fontchooser-symbolic

**Comment by oscfdezdz** [comment]
By reducing them 0.5x they look much smaller than before, I guess it changed the size of the new ones.

**Comment by flxzt** [comment]
yeah, but I am misremembering it, it probably wasn't exactly 0.5x. I'll quickly make adjustments and push to the branch.

**Comment by oscfdezdz** [comment]
I went with 0.25x and it's still not the same size, but it's pretty similar.

**Comment by flxzt** [comment]
ah you adjusted it already. Looks good to me now

**Pull request merged**
